---
title:
output: html_document
---

```{r warning=FALSE, message=FALSE, error=FALSE}
library(readr)
library(plm)
library(dplyr)

d <- read_csv("../../merge_new_data/updated_analysis_data_with_8_15.csv")

remove <- c("Country.y", "iso2c", "MS.MIL.XPND.CN")
d <- d[, !(names(d) %in% remove)]

## calculate % mentions for each topic by country/year group------

d <- d %>%
    group_by(Country.x, Year) %>%
    mutate(sMentions = Mentions / sum(Mentions, na.rm=TRUE)) %>%
    mutate(sRecommendations = Recommendations / sum(Recommendations, na.rm=TRUE))

d <- d %>% ungroup()
d$sMentions_logit <- log(d$sMentions / (1 - d$sMentions))
d$sRecommendations_logit <- log(d$sRecommendations / (1 - d$sRecommendations))
```


# Choose the set of Explanatory Variables

```{r warning=FALSE, message=FALSE, error=FALSE}
### explanatory variables-----
vars <- c(
           "FP.CPI.TOTL.ZG", # Inflation, consumer prices (annual %)
           "BN.CAB.XOKA.GD.ZS", # Current Account Balance as % of GDP
#          "IC.FRM.BNKS.ZS", # Firms using banks to finance investment (% of firms)
#          "BX.KLT.DINV.WD.GD.ZS", # Foreign direct investment, net inflows (% of GDP) (Replace Foreign direct investment net)
#          "BX.TRF.PWKR.DT.GD.ZS", # Personal remittances, received (% of GDP)
#          "BG.GSR.NFSV.GD.ZS", # Trade in services (% of GDP)
#          "NV.AGR.TOTL.ZS", # Agriculture, forestry, and fishing, value added (% of GDP)
#          "NE.EXP.GNFS.ZS", # Exports of goods and services (% of GDP)
           "NY.GDP.MKTP.KD.ZG", # GDP growth (annual %)
#          "NY.GDP.PCAP.KD.ZG", # GDP per capita growth (annual %)
#          "NY.GDS.TOTL.ZS", # Gross domestic savings (% of GDP)
#          "NE.IMP.GNFS.ZS", # Imports of goods and services (% of GDP)
           "SL.TLF.CACT.ZS", # Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)
           "BCG_GALM_G01_XDC" # Central government debt, total (% of GDP)
          )

mentions_form <- as.formula(paste("sMentions_logit ~", paste(vars, collapse="+")))

recommendations_form <- as.formula(paste("sRecommendations_logit ~", paste(vars, collapse="+")))
```

# Estimate Models

## Between Models

```{r warning=FALSE, message=FALSE, error=FALSE}
for (topic in unique(d$Topic)){
    tmp <- subset(d, Topic == topic)
    tmp <- pdata.frame(tmp, index = c("Country.x", "Year"), drop.index=TRUE, row.names=TRUE)
    writeLines(paste0("\n>>>>>Scaled Mentions: ", topic, "<<<<<\n"))
    print(summary(plm(mentions_form, data = tmp, model = "between")))
    writeLines(paste0("\n>>>Scaled Recommendations: ", topic, "<<<<<\n"))
    e <- simpleError("NA data error")
    tryCatch(print(summary(plm(recommendations_form, data = tmp, model = "between"))),
             error = function(e) e)
}
```

## Within (Fixed-Effects) Models

### Time, but no Individual Effects 

```{r}
for (topic in unique(d$Topic)){
    tmp <- subset(d, Topic == topic)
    tmp <- pdata.frame(tmp, index = c("Country.x", "Year"), drop.index=TRUE, row.names=TRUE)
    writeLines(paste0("\n>>>>>Scaled Mentions: ", topic, "<<<<<\n"))
    print(summary(plm(mentions_form, data = tmp, model = "within", effect = "time")))
    writeLines(paste0("\n>>>Scaled Recommendations: ", topic, "<<<<<\n"))
    print(summary(plm(recommendations_form, data = tmp, model = "within", effect = "time")))
}
## estimate models
## summary(plm(mentions_form, data = ed, model = "between", effect = "individual"))
## summary(plm(mentions_form, data = ed, model = "within", effect = "twoways"))
## summary(plm(mentions_form, data = ed, model = "within", effect = "individual"))
## summary(plm(mentions_form, data = ed, model = "within", effect = "time"))
```

### Both Time and Individual Effects

```{r}

for (topic in unique(d$Topic)){
    tmp <- subset(d, Topic == topic)
    tmp <- pdata.frame(tmp, index = c("Country.x", "Year"), drop.index=TRUE, row.names=TRUE)
    writeLines(paste0("\n>>>>>Scaled Mentions: ", topic, "<<<<<\n"))
    print(summary(plm(mentions_form, data = tmp, model = "within", effect = "twoways")))
    writeLines(paste0("\n>>>Scaled Recommendations: ", topic, "<<<<<\n"))
    print(summary(plm(recommendations_form, data = tmp, model = "within", effect = "twoways")))
}


```

### Individual, but No Time Effects

### Both Time and Individual Effects

```{r}

for (topic in unique(d$Topic)){
    tmp <- subset(d, Topic == topic)
    tmp <- pdata.frame(tmp, index = c("Country.x", "Year"), drop.index=TRUE, row.names=TRUE)
    writeLines(paste0("\n>>>>>Scaled Mentions: ", topic, "<<<<<\n"))
    print(summary(plm(mentions_form, data = tmp, model = "within", effect = "individual")))
    writeLines(paste0("\n>>>Scaled Recommendations: ", topic, "<<<<<\n"))
    print(summary(plm(recommendations_form, data = tmp, model = "within", effect = "individual")))
}


```
